adrih1/caravana

Gemfile, Gemfile.lock, app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/layouts/application.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20220822132806_devise_create_users.rb, db/schema.rb, test/models/user_test.rb
=> devise done

app/models/user.rb, app/models/van.rb, db/migrate/20220822135823_create_vans.rb, db/schema.rb, test/models/van_test.rb
Create the van model with all validations and dependencies.
(Add the user dependency "has_many: vans")
=> add vans model with validations and dependencies

db/migrate/20220822141818_add_columns_to_users.rb, db/schema.rb
Added columns to User Model. 
Dependencies still to be done with booking model
=> Adding Colums to User Model

config/routes.rb
i just created the routes with Antoine
=> routes initialized

Gemfile.lock, app/controllers/bookings_controller.rb, app/controllers/users_controller.rb, app/controllers/vans_controller.rb, test/controllers/bookings_controller_test.rb, test/controllers/users_controller_test.rb, test/controllers/vans_controller_test.rb
=> Intialize controllers

Gemfile, Gemfile.lock, config/routes.rb, db/schema.rb, db/seeds.rb
- Add  Faker gem to gemfile
- Create seed for Users and Vans
- Correct routes synthax (only was missing ':')
=> add faker gem, created seed, corrected routes

app/controllers/vans_controller.rb, config/routes.rb, db/schema.rb
Mise en place des actions du controller vans
=> controller van created

app/assets/stylesheets/pages/_dashboard.scss, app/assets/stylesheets/pages/_index.scss, app/controllers/pages_controller.rb, app/views/pages/dashboard.html.erb, app/views/pages/my_vans.html.erb, config/routes.rb
implementation dashboard/my_vans views, il ne reste plus qu'à les lier aux utilisateurs
=> implementation dashboard/my_vans views

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/views/vans/index.html.erb, db/seeds.rb
Edited the show to make a grid and created the V-0 van card templates.
=> van card and grid on the index view

app/controllers/bookings_controller.rb, app/views/vans/index.html.erb
Fix layout problem on show
Fix synthax error on booking action: create.
=> fix layout problem on show

app/controllers/bookings_controller.rb, app/controllers/vans_controller.rb, app/views/vans/show.html.erb, config/routes.rb
Create: Booking new & create
Adapt  in consequence the routes & the van/show & the vans/controller
=> Create booking new/create

app/assets/stylesheets/components/_connexion-form.scss, app/views/pages/home.html.erb
• Actualized Card Dsiplay with Antoine's Design
• Sign Out Fixed 
• Forms Log In and Sign In reviewed
=> Fixed Page Home and Log In

app/assets/stylesheets/pages/_dashboard.scss, app/assets/stylesheets/pages/_index.scss, package-lock.json, package.json, yarn.lock
Test of filter non conclusive 
Suppression of "body display flex"
Corrections if additional small mistakes
=> test de filtre

app/controllers/vans_controller.rb, app/views/vans/_form.html.erb, app/views/vans/edit.html.erb, app/views/vans/new.html.erb, config/routes.rb
=> Create a Van

app/views/pages/home.html.erb
=> Pundit fixed for page homes

app/assets/stylesheets/pages/_dashboard.scss, app/controllers/bookings_controller.rb, app/controllers/vans_controller.rb
Redirection vers dashboard quand book a van
=> Redirectionbookavan

app/assets/stylesheets/components/_navbar.scss, app/controllers/bookings_controller.rb, yarn.lock
=> Pundit for Booking

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/pages/_dashboard.scss, app/views/pages/dashboard.html.erb, yarn.lock
Design card mes bookings sur dashboard done (juste le front).
=> card dashboard done

app/assets/stylesheets/components/_navbar.scss, app/javascript/controllers/navbar_controller.js, app/views/shared/_navbar.html.erb
Add company name next to logo
Fixed navbar navbar
Reduce logo
Space between connexion buttons
=> Better Navbar

.gitignore, Gemfile, Gemfile.lock, app/controllers/vans_controller.rb, app/models/van.rb, app/views/shared/_form.html.erb, app/views/vans/index.html.erb, app/views/vans/show.html.erb, config/environments/development.rb, config/storage.yml, db/migrate/20220823150051_create_active_storage_tables.active_storage.rb, db/schema.rb
Gem Cloudinary et active storage
=> Cloudinary

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_dashboard.scss, app/views/pages/dashboard.html.erb, app/views/shared/_navbar.html.erb, app/views/vans/index.html.erb, app/views/vans/show.html.erb
=> First Fix on Dashboard

app/assets/stylesheets/components/_card.scss, app/controllers/pages_controller.rb, app/views/pages/dashboard.html.erb, app/views/pages/home.html.erb, app/views/vans/index.html.erb
Modify home grid: 4 columns, responsive.
Started iteration on bookings display in dashboard. Need to confirm if it works by creating several bookings with the same user.
=> Modify home grid + start iteration on dashboard for bookings

app/controllers/vans_controller.rb, app/views/shared/_form.html.erb, app/views/vans/edit.html.erb, app/views/vans/new.html.erb, db/migrate/20220824082223_add_columns_to_vans.rb, db/schema.rb
• Create Van Adapted with new inputs for the columns
• Strong Params in the Vans Controller Done
=> Van Model - New Columns - Title and capacity

app/assets/stylesheets/components/_card.scss, app/views/pages/dashboard.html.erb, app/views/pages/home.html.erb
• Better alignement and spacement of control buttons on a van
=> Better Display of En savoir Edit Remove

.gitignore, app/models/van.rb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb, config/environments/development.rb, config/environments/production.rb, config/storage.yml, db/seeds.rb
Fix cloudinary in several files (synthax, lines missings etc...)
Update the seed to work with cloudinary.
Modify Navbar nav redirection.
=> Fix cloudinary, add cloudinary in index, update seed

app/controllers/pages_controller.rb, app/controllers/vans_controller.rb, app/views/pages/dashboard.html.erb
Show is now available for visitors (even if not logged in) 
Still have to display modal when not connected, instead of old login form
=> Show Available for visitors also

.gitignore, app/controllers/pages_controller.rb, app/controllers/vans_controller.rb
Small fixe on typo error for destroy method on van
=> Typo Error on destroy

app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/views/shared/_login.html.erb, app/views/shared/_signup.html.erb
=> modal en partial

app/assets/stylesheets/pages/_van.scss, app/views/vans/show.html.erb
=> Show Padding Fix

app/views/pages/dashboard.html.erb, db/seeds.rb
Good Van Booking Display 
TODO : Fix Image display on bottom of card
=> DashBoard Booking Display - good

app/views/pages/dashboard.html.erb, app/views/pages/home.html.erb, db/seeds.rb
• Better display of van display
=> Van Display Card : Index and Dashboard

app/views/vans/show.html.erb, db/seeds.rb
=> Map Delete for Hiroku on show

db/seeds.rb
=> Better Photos for Vans

app/views/pages/home.html.erb
=> link on homepage

app/views/pages/dashboard.html.erb
=> frontend tweaks

app/views/pages/dashboard.html.erb, app/views/pages/my_vans.html.erb, app/views/shared/_navbar.html.erb, app/views/vans/show.html.erb
=> add a lot of features

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_address_autocomplete.scss, app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_index.scss, app/controllers/vans_controller.rb, app/javascript/controllers/index.js, app/javascript/controllers/location_autocomplete_controller.js, app/javascript/controllers/map_controller.js, app/models/van.rb, app/views/layouts/application.html.erb, app/views/pages/my_vans.html.erb, app/views/shared/_form.html.erb, app/views/shared/_navbar.html.erb, app/views/vans/new.html.erb, app/views/vans/show.html.erb, config/initializers/geocoder.rb, db/migrate/20220824235308_add_coordinates_to_vans.rb, db/schema.rb
- Update the navbar
- Add map
- Changed form inputs
- Add font
=> improve some features (navbar, map etc...)

app/assets/stylesheets/components/_connexion-form.scss, app/assets/stylesheets/pages/_van.scss, app/views/vans/show.html.erb, db/seeds.rb
• Seed : 6 vans created / 5 still generated with Faker
• Show : Mileage better display / Padding on top div / Id made on the last "p" to align correctly
=> Seed Improve / Show Small Front Fix

app/assets/stylesheets/pages/_dashboard.scss, app/views/pages/dashboard.html.erb
• Icons Sidebar Changed 
• Added if when bookings don't exist 
• Better style for Time
=> Dashboard-New

app/assets/stylesheets/components/_connexion-form.scss, app/assets/stylesheets/components/_form.scss, app/controllers/vans_controller.rb, app/models/van.rb, app/views/shared/_form.html.erb, app/views/vans/new.html.erb, app/views/vans/show.html.erb, db/seeds.rb
Basic front on the create van.
Create van works.
=> create new van basic front-end

app/assets/stylesheets/components/_address_autocomplete.scss, app/assets/stylesheets/components/_form.scss, app/controllers/vans_controller.rb, app/javascript/controllers/map_controller.js, app/views/vans/show.html.erb
=> modify small things show

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/pages/_dashboard.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_my_vans.scss, app/views/pages/dashboard.html.erb, app/views/pages/my_vans.html.erb, app/views/vans/new.html.erb
=> My Vans Front End

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_icon.scss, app/assets/stylesheets/components/_index.scss, app/controllers/bookings_controller.rb, app/views/pages/dashboard.html.erb, app/views/pages/home.html.erb, app/views/pages/my_vans.html.erb
Button classic "Add a van" + icon delete
=> Button delete + classic

app/views/pages/home.html.erb
=> fix carousel

app/javascript/application.js
=> Javascript fix on flt picker

app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
=> fix bugs on homepage

app/assets/stylesheets/components/_form.scss, app/views/vans/show.html.erb
=> fix and optimize on show

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
=> update logo et navbar

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/pages/_my_vans.scss, app/assets/stylesheets/pages/_van.scss, app/views/pages/my_vans.html.erb
=> Dashboard front changes

app/assets/stylesheets/pages/_home.scss
=> couleur search

app/assets/stylesheets/components/_address_autocomplete.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/pages/_new.scss, app/views/shared/_form.html.erb, app/views/vans/new.html.erb
Frontend done for the van new page
=> van new done

app/assets/stylesheets/components/_card.scss, app/views/pages/home.html.erb
Update the card to make it more colorful.
=> card update

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/pages/_dashboard.scss
• Color changed
• Automatic text decoration underline from bootstrap deleted
=> Dashboard Icons Sidebard

app/views/pages/dashboard.html.erb
Scenario where user has no bookings
=> Dashboard Empty Scenario

app/assets/stylesheets/pages/_van.scss, app/views/pages/my_vans.html.erb, app/views/vans/show.html.erb
• Total price before the book button
• "A Calculer" useless text deleted
• Delete Icon aligned with text in "My Vans" page
=> Dashboard / Show Better Display

app/assets/stylesheets/components/_connexion-form.scss, app/assets/stylesheets/pages/_van.scss, app/views/shared/_navbar.html.erb, app/views/vans/show.html.erb
Optimize the show and add connexions.
=> add connexion and optimize show

app/controllers/vans_controller.rb, app/javascript/controllers/map_controller.js, app/views/vans/show.html.erb
=> Connectique

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_ratings.scss, app/views/devise/registrations/new.html.erb, app/views/pages/home.html.erb, app/views/reviews/new.html.erb, app/views/vans/show.html.erb
=> review page done

app/views/reviews/new.html.erb, app/views/shared/_form.html.erb, app/views/shared/_navbar.html.erb, app/views/vans/new.html.erb, app/views/vans/show.html.erb
=> navbar amelioration, forms ameliorations

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/pages/_dashboard.scss, app/assets/stylesheets/pages/_my_vans.scss, app/controllers/pages_controller.rb, app/views/pages/dashboard.html.erb, app/views/pages/my_vans.html.erb
• Back-End for my vans done 
• Some front end done
•TODO : add banner
• TODO : add scenario for no bookings on my vans 
• TODO : add scenario for no vans created
=> My Vans Back End and some front

app/assets/stylesheets/components/_card.scss
=> fixed missing { in css

app/assets/stylesheets/components/_button.scss, app/views/pages/dashboard.html.erb, app/views/shared/_banner.html.erb
• Date styled 
• Button review styled
=> Date and Review Button styled

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_icon.scss, app/views/pages/dashboard.html.erb, app/views/pages/my_vans.html.erb, app/views/vans/show.html.erb
=> Dashboard my vans finalization

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_dashboard.scss, app/views/layouts/application.html.erb, app/views/pages/dashboard.html.erb, app/views/pages/my_vans.html.erb, app/views/shared/_banner_bis.html.erb, db/seeds.rb
• Banner Fixed
• DashBoard and My Vans Finished
• New Seed
=> Huge Evolution

db/seeds.rb
=> Seed Review Delete

db/seeds.rb
=> New Seed No bookings

app/views/shared/_banner.html.erb, app/views/shared/_banner_bis.html.erb
Space after Welcome on dashboard and my vans
=> Space Name

db/seeds.rb
=> Last version pleaaaaase

db/seeds.rb
=> Seed Final Version with order

app/views/devise/sessions/new.html.erb, app/views/pages/error.html.erb, app/views/shared/_login_form.html.erb
• Secondary Log In Page for different root of connection if needed
=> Log In Second Page in case modal doesn't work
